/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AccessRequestApi,
  AdminApi,
  AuthenticationApi,
  DatasetApi,
  ESRIApi,
  GraphApi,
  HarvestApi,
  ImageApi,
  ImportApi,
  ManageDatasetApi,
  ManageLayerApi,
  OgcApiTilesApi,
  OGCAPIApi,
  QueryDatasetApi,
  QueryLayerApi,
  ServiceDefinitionApi,
  ShapefileApi,
  StatusApi,
  TemplateApi,
  WCSApi,
  WFSApi,
  WMSApi,
  WMTSApi,
  WmtsRestApi,
  DataRequestApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { AgrimetricsCustom } from "./client-custom";

export class Agrimetrics extends AgrimetricsCustom {
  readonly accessRequest: AccessRequestApi;
  readonly admin: AdminApi;
  readonly authentication: AuthenticationApi;
  readonly dataset: DatasetApi;
  readonly eSRI: ESRIApi;
  readonly graph: GraphApi;
  readonly harvest: HarvestApi;
  readonly image: ImageApi;
  readonly import: ImportApi;
  readonly manageDataset: ManageDatasetApi;
  readonly manageLayer: ManageLayerApi;
  readonly ogcApiTiles: OgcApiTilesApi;
  readonly oGCAPI: OGCAPIApi;
  readonly queryDataset: QueryDatasetApi;
  readonly queryLayer: QueryLayerApi;
  readonly serviceDefinition: ServiceDefinitionApi;
  readonly shapefile: ShapefileApi;
  readonly status: StatusApi;
  readonly template: TemplateApi;
  readonly wCS: WCSApi;
  readonly wFS: WFSApi;
  readonly wMS: WMSApi;
  readonly wMTS: WMTSApi;
  readonly wmtsRest: WmtsRestApi;
  readonly dataRequest: DataRequestApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.accessRequest = new AccessRequestApi(configuration);
    this.admin = new AdminApi(configuration);
    this.authentication = new AuthenticationApi(configuration);
    this.dataset = new DatasetApi(configuration);
    this.eSRI = new ESRIApi(configuration);
    this.graph = new GraphApi(configuration);
    this.harvest = new HarvestApi(configuration);
    this.image = new ImageApi(configuration);
    this.import = new ImportApi(configuration);
    this.manageDataset = new ManageDatasetApi(configuration);
    this.manageLayer = new ManageLayerApi(configuration);
    this.ogcApiTiles = new OgcApiTilesApi(configuration);
    this.oGCAPI = new OGCAPIApi(configuration);
    this.queryDataset = new QueryDatasetApi(configuration);
    this.queryLayer = new QueryLayerApi(configuration);
    this.serviceDefinition = new ServiceDefinitionApi(configuration);
    this.shapefile = new ShapefileApi(configuration);
    this.status = new StatusApi(configuration);
    this.template = new TemplateApi(configuration);
    this.wCS = new WCSApi(configuration);
    this.wFS = new WFSApi(configuration);
    this.wMS = new WMSApi(configuration);
    this.wMTS = new WMTSApi(configuration);
    this.wmtsRest = new WmtsRestApi(configuration);
    this.dataRequest = new DataRequestApi(configuration);
  }

}
