/* tslint:disable */
/* eslint-disable */
/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { RestError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ESRIApi - axios parameter creator
 * @export
 */
export const ESRIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Query the given dataset using ESRI Rest Services 
         * @summary ESRI REST Service query
         * @param {string} datasetId 
         * @param {string} paramOne Additional path element
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restServiceQuery: async (datasetId: string, paramOne: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'datasetId' is not null or undefined
            assertParamExists('restServiceQuery', 'datasetId', datasetId)
            // verify required parameter 'paramOne' is not null or undefined
            assertParamExists('restServiceQuery', 'paramOne', paramOne)
            const localVarPath = `/rest/services/{datasetId}/{paramOne}`
                .replace(`{${"datasetId"}}`, encodeURIComponent(String(datasetId !== undefined ? datasetId : `-datasetId-`)))
                .replace(`{${"paramOne"}}`, encodeURIComponent(String(paramOne !== undefined ? paramOne : `-paramOne-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/rest/services/{datasetId}/{paramOne}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Query the given dataset using ESRI Rest Services 
         * @summary ESRI REST Service query
         * @param {string} datasetId 
         * @param {string} paramOne Additional path element
         * @param {string} paramTwo Additional path element
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restServiceQuery_1: async (datasetId: string, paramOne: string, paramTwo: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'datasetId' is not null or undefined
            assertParamExists('restServiceQuery_1', 'datasetId', datasetId)
            // verify required parameter 'paramOne' is not null or undefined
            assertParamExists('restServiceQuery_1', 'paramOne', paramOne)
            // verify required parameter 'paramTwo' is not null or undefined
            assertParamExists('restServiceQuery_1', 'paramTwo', paramTwo)
            const localVarPath = `/rest/services/{datasetId}/{paramOne}/{paramTwo}`
                .replace(`{${"datasetId"}}`, encodeURIComponent(String(datasetId !== undefined ? datasetId : `-datasetId-`)))
                .replace(`{${"paramOne"}}`, encodeURIComponent(String(paramOne !== undefined ? paramOne : `-paramOne-`)))
                .replace(`{${"paramTwo"}}`, encodeURIComponent(String(paramTwo !== undefined ? paramTwo : `-paramTwo-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/rest/services/{datasetId}/{paramOne}/{paramTwo}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ESRIApi - functional programming interface
 * @export
 */
export const ESRIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ESRIApiAxiosParamCreator(configuration)
    return {
        /**
         * Query the given dataset using ESRI Rest Services 
         * @summary ESRI REST Service query
         * @param {ESRIApiRestServiceQueryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async restServiceQuery(requestParameters: ESRIApiRestServiceQueryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restServiceQuery(requestParameters.datasetId, requestParameters.paramOne, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Query the given dataset using ESRI Rest Services 
         * @summary ESRI REST Service query
         * @param {ESRIApiRestServiceQuery0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async restServiceQuery_1(requestParameters: ESRIApiRestServiceQuery0Request, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restServiceQuery_1(requestParameters.datasetId, requestParameters.paramOne, requestParameters.paramTwo, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ESRIApi - factory interface
 * @export
 */
export const ESRIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ESRIApiFp(configuration)
    return {
        /**
         * Query the given dataset using ESRI Rest Services 
         * @summary ESRI REST Service query
         * @param {ESRIApiRestServiceQueryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restServiceQuery(requestParameters: ESRIApiRestServiceQueryRequest, options?: AxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.restServiceQuery(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Query the given dataset using ESRI Rest Services 
         * @summary ESRI REST Service query
         * @param {ESRIApiRestServiceQuery0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restServiceQuery_1(requestParameters: ESRIApiRestServiceQuery0Request, options?: AxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.restServiceQuery_1(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for restServiceQuery operation in ESRIApi.
 * @export
 * @interface ESRIApiRestServiceQueryRequest
 */
export type ESRIApiRestServiceQueryRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof ESRIApiRestServiceQuery
    */
    readonly datasetId: string
    
    /**
    * Additional path element
    * @type {string}
    * @memberof ESRIApiRestServiceQuery
    */
    readonly paramOne: string
    
}

/**
 * Request parameters for restServiceQuery_1 operation in ESRIApi.
 * @export
 * @interface ESRIApiRestServiceQuery0Request
 */
export type ESRIApiRestServiceQuery0Request = {
    
    /**
    * 
    * @type {string}
    * @memberof ESRIApiRestServiceQuery0
    */
    readonly datasetId: string
    
    /**
    * Additional path element
    * @type {string}
    * @memberof ESRIApiRestServiceQuery0
    */
    readonly paramOne: string
    
    /**
    * Additional path element
    * @type {string}
    * @memberof ESRIApiRestServiceQuery0
    */
    readonly paramTwo: string
    
}

/**
 * ESRIApiGenerated - object-oriented interface
 * @export
 * @class ESRIApiGenerated
 * @extends {BaseAPI}
 */
export class ESRIApiGenerated extends BaseAPI {
    /**
     * Query the given dataset using ESRI Rest Services 
     * @summary ESRI REST Service query
     * @param {ESRIApiRestServiceQueryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ESRIApiGenerated
     */
    public restServiceQuery(requestParameters: ESRIApiRestServiceQueryRequest, options?: AxiosRequestConfig) {
        return ESRIApiFp(this.configuration).restServiceQuery(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Query the given dataset using ESRI Rest Services 
     * @summary ESRI REST Service query
     * @param {ESRIApiRestServiceQuery0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ESRIApiGenerated
     */
    public restServiceQuery_1(requestParameters: ESRIApiRestServiceQuery0Request, options?: AxiosRequestConfig) {
        return ESRIApiFp(this.configuration).restServiceQuery_1(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
