/* tslint:disable */
/* eslint-disable */
/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * GraphApi - axios parameter creator
 * @export
 */
export const GraphApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List All Concepts Available in Agrimetrics Ontology Graph.
         * @summary List all concepts in linked data graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listConcepts: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/linked-data/concepts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/linked-data/concepts',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GraphApi - functional programming interface
 * @export
 */
export const GraphApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GraphApiAxiosParamCreator(configuration)
    return {
        /**
         * List All Concepts Available in Agrimetrics Ontology Graph.
         * @summary List all concepts in linked data graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listConcepts(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listConcepts(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * GraphApi - factory interface
 * @export
 */
export const GraphApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GraphApiFp(configuration)
    return {
        /**
         * List All Concepts Available in Agrimetrics Ontology Graph.
         * @summary List all concepts in linked data graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listConcepts(options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.listConcepts(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GraphApiGenerated - object-oriented interface
 * @export
 * @class GraphApiGenerated
 * @extends {BaseAPI}
 */
export class GraphApiGenerated extends BaseAPI {
    /**
     * List All Concepts Available in Agrimetrics Ontology Graph.
     * @summary List all concepts in linked data graph.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GraphApiGenerated
     */
    public listConcepts(options?: AxiosRequestConfig) {
        return GraphApiFp(this.configuration).listConcepts(options).then((request) => request(this.axios, this.basePath));
    }
}
