/* tslint:disable */
/* eslint-disable */
/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ImageApi - axios parameter creator
 * @export
 */
export const ImageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get an image referenced on a data set. This will always return the raw image data.
         * @summary Get an image used in the catalogue.
         * @param {'custom' | 'unsplash'} imageType 
         * @param {string} imageId 
         * @param {'true' | 'false'} [thumbnail] Whether to provide a thumbnail image. If set to true and no thumbnail exists, the full image will be returned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRawImage: async (imageType: 'custom' | 'unsplash', imageId: string, thumbnail?: 'true' | 'false', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'imageType' is not null or undefined
            assertParamExists('getRawImage', 'imageType', imageType)
            // verify required parameter 'imageId' is not null or undefined
            assertParamExists('getRawImage', 'imageId', imageId)
            const localVarPath = `/images/{imageType}/{imageId}`
                .replace(`{${"imageType"}}`, encodeURIComponent(String(imageType !== undefined ? imageType : `-imageType-`)))
                .replace(`{${"imageId"}}`, encodeURIComponent(String(imageId !== undefined ? imageId : `-imageId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            if (thumbnail !== undefined) {
                localVarQueryParameter['thumbnail'] = thumbnail;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/images/{imageType}/{imageId}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ImageApi - functional programming interface
 * @export
 */
export const ImageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ImageApiAxiosParamCreator(configuration)
    return {
        /**
         * Get an image referenced on a data set. This will always return the raw image data.
         * @summary Get an image used in the catalogue.
         * @param {ImageApiGetRawImageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRawImage(requestParameters: ImageApiGetRawImageRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRawImage(requestParameters.imageType, requestParameters.imageId, requestParameters.thumbnail, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ImageApi - factory interface
 * @export
 */
export const ImageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ImageApiFp(configuration)
    return {
        /**
         * Get an image referenced on a data set. This will always return the raw image data.
         * @summary Get an image used in the catalogue.
         * @param {ImageApiGetRawImageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRawImage(requestParameters: ImageApiGetRawImageRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getRawImage(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getRawImage operation in ImageApi.
 * @export
 * @interface ImageApiGetRawImageRequest
 */
export type ImageApiGetRawImageRequest = {
    
    /**
    * 
    * @type {'custom' | 'unsplash'}
    * @memberof ImageApiGetRawImage
    */
    readonly imageType: 'custom' | 'unsplash'
    
    /**
    * 
    * @type {string}
    * @memberof ImageApiGetRawImage
    */
    readonly imageId: string
    
    /**
    * Whether to provide a thumbnail image. If set to true and no thumbnail exists, the full image will be returned
    * @type {'true' | 'false'}
    * @memberof ImageApiGetRawImage
    */
    readonly thumbnail?: 'true' | 'false'
    
}

/**
 * ImageApiGenerated - object-oriented interface
 * @export
 * @class ImageApiGenerated
 * @extends {BaseAPI}
 */
export class ImageApiGenerated extends BaseAPI {
    /**
     * Get an image referenced on a data set. This will always return the raw image data.
     * @summary Get an image used in the catalogue.
     * @param {ImageApiGetRawImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImageApiGenerated
     */
    public getRawImage(requestParameters: ImageApiGetRawImageRequest, options?: AxiosRequestConfig) {
        return ImageApiFp(this.configuration).getRawImage(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
