/* tslint:disable */
/* eslint-disable */
/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GeoJSONPolygon } from '../models';
// @ts-ignore
import { RestError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ShapefileApi - axios parameter creator
 * @export
 */
export const ShapefileApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * > :warning: **This is an Agrimetrics internal operation. It relies on information which is not exposed externally.**  Receive a shapefile and return GeoJson for explore page 
         * @summary Receive a shapefile and return GeoJson
         * @param {Uint8Array | File | buffer.File} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertToGeoJson: async (body: Uint8Array | File | buffer.File, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('convertToGeoJson', 'body', body)
            const localVarPath = `/shapefile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/zipped-shapefile';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: body,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/shapefile',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ShapefileApi - functional programming interface
 * @export
 */
export const ShapefileApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ShapefileApiAxiosParamCreator(configuration)
    return {
        /**
         * > :warning: **This is an Agrimetrics internal operation. It relies on information which is not exposed externally.**  Receive a shapefile and return GeoJson for explore page 
         * @summary Receive a shapefile and return GeoJson
         * @param {ShapefileApiConvertToGeoJsonRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async convertToGeoJson(requestParameters: ShapefileApiConvertToGeoJsonRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GeoJSONPolygon>> {
            const body: Uint8Array | File | buffer.File = requestParameters;
            const localVarAxiosArgs = await localVarAxiosParamCreator.convertToGeoJson(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ShapefileApi - factory interface
 * @export
 */
export const ShapefileApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ShapefileApiFp(configuration)
    return {
        /**
         * > :warning: **This is an Agrimetrics internal operation. It relies on information which is not exposed externally.**  Receive a shapefile and return GeoJson for explore page 
         * @summary Receive a shapefile and return GeoJson
         * @param {ShapefileApiConvertToGeoJsonRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertToGeoJson(requestParameters: ShapefileApiConvertToGeoJsonRequest, options?: AxiosRequestConfig): AxiosPromise<GeoJSONPolygon> {
            return localVarFp.convertToGeoJson(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for convertToGeoJson operation in ShapefileApi.
 * @export
 * @interface ShapefileApiConvertToGeoJsonRequest
 */
export type ShapefileApiConvertToGeoJsonRequest = Uint8Array | File | buffer.File

/**
 * ShapefileApiGenerated - object-oriented interface
 * @export
 * @class ShapefileApiGenerated
 * @extends {BaseAPI}
 */
export class ShapefileApiGenerated extends BaseAPI {
    /**
     * > :warning: **This is an Agrimetrics internal operation. It relies on information which is not exposed externally.**  Receive a shapefile and return GeoJson for explore page 
     * @summary Receive a shapefile and return GeoJson
     * @param {ShapefileApiConvertToGeoJsonRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShapefileApiGenerated
     */
    public convertToGeoJson(requestParameters: ShapefileApiConvertToGeoJsonRequest, options?: AxiosRequestConfig) {
        return ShapefileApiFp(this.configuration).convertToGeoJson(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
