/* tslint:disable */
/* eslint-disable */
/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { RestError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * WMSApi - axios parameter creator
 * @export
 */
export const WMSApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Query the given layer with the OpenGIS® Web Map Service interface standard 
         * @summary Web Map Service (WMS) query
         * @param {string} datasetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryLayerWithOpenGIS: async (datasetId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'datasetId' is not null or undefined
            assertParamExists('queryLayerWithOpenGIS', 'datasetId', datasetId)
            const localVarPath = `/datasets/{datasetId}/wms`
                .replace(`{${"datasetId"}}`, encodeURIComponent(String(datasetId !== undefined ? datasetId : `-datasetId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/datasets/{datasetId}/wms',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Query the given data set with the OpenGIS® Web Map Service interface standard 
         * @summary Web Maps Service (WMS) query
         * @param {string} datasetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryWithOpenGis: async (datasetId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'datasetId' is not null or undefined
            assertParamExists('queryWithOpenGis', 'datasetId', datasetId)
            const localVarPath = `/datasets/{datasetId}/wms`
                .replace(`{${"datasetId"}}`, encodeURIComponent(String(datasetId !== undefined ? datasetId : `-datasetId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'HEAD', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/datasets/{datasetId}/wms',
                httpMethod: 'HEAD'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WMSApi - functional programming interface
 * @export
 */
export const WMSApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WMSApiAxiosParamCreator(configuration)
    return {
        /**
         * Query the given layer with the OpenGIS® Web Map Service interface standard 
         * @summary Web Map Service (WMS) query
         * @param {WMSApiQueryLayerWithOpenGISRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queryLayerWithOpenGIS(requestParameters: WMSApiQueryLayerWithOpenGISRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.queryLayerWithOpenGIS(requestParameters.datasetId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Query the given data set with the OpenGIS® Web Map Service interface standard 
         * @summary Web Maps Service (WMS) query
         * @param {WMSApiQueryWithOpenGisRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queryWithOpenGis(requestParameters: WMSApiQueryWithOpenGisRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.queryWithOpenGis(requestParameters.datasetId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * WMSApi - factory interface
 * @export
 */
export const WMSApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WMSApiFp(configuration)
    return {
        /**
         * Query the given layer with the OpenGIS® Web Map Service interface standard 
         * @summary Web Map Service (WMS) query
         * @param {WMSApiQueryLayerWithOpenGISRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryLayerWithOpenGIS(requestParameters: WMSApiQueryLayerWithOpenGISRequest, options?: AxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.queryLayerWithOpenGIS(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Query the given data set with the OpenGIS® Web Map Service interface standard 
         * @summary Web Maps Service (WMS) query
         * @param {WMSApiQueryWithOpenGisRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryWithOpenGis(requestParameters: WMSApiQueryWithOpenGisRequest, options?: AxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.queryWithOpenGis(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for queryLayerWithOpenGIS operation in WMSApi.
 * @export
 * @interface WMSApiQueryLayerWithOpenGISRequest
 */
export type WMSApiQueryLayerWithOpenGISRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof WMSApiQueryLayerWithOpenGIS
    */
    readonly datasetId: string
    
}

/**
 * Request parameters for queryWithOpenGis operation in WMSApi.
 * @export
 * @interface WMSApiQueryWithOpenGisRequest
 */
export type WMSApiQueryWithOpenGisRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof WMSApiQueryWithOpenGis
    */
    readonly datasetId: string
    
}

/**
 * WMSApiGenerated - object-oriented interface
 * @export
 * @class WMSApiGenerated
 * @extends {BaseAPI}
 */
export class WMSApiGenerated extends BaseAPI {
    /**
     * Query the given layer with the OpenGIS® Web Map Service interface standard 
     * @summary Web Map Service (WMS) query
     * @param {WMSApiQueryLayerWithOpenGISRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WMSApiGenerated
     */
    public queryLayerWithOpenGIS(requestParameters: WMSApiQueryLayerWithOpenGISRequest, options?: AxiosRequestConfig) {
        return WMSApiFp(this.configuration).queryLayerWithOpenGIS(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Query the given data set with the OpenGIS® Web Map Service interface standard 
     * @summary Web Maps Service (WMS) query
     * @param {WMSApiQueryWithOpenGisRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WMSApiGenerated
     */
    public queryWithOpenGis(requestParameters: WMSApiQueryWithOpenGisRequest, options?: AxiosRequestConfig) {
        return WMSApiFp(this.configuration).queryWithOpenGis(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
