/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Accrual periodicity options
 * @export
 * @enum {string}
 */
export type AccrualPeriodicity = 'Hourly' | 'Daily' | 'Three times a week' | 'Semiweekly' | 'Weekly' | 'Three times a month' | 'Biweekly' | 'Semimonthly' | 'Monthly' | 'Bimonthly' | 'Quarterly' | 'Three times a year' | 'Semiannual' | 'Annual' | 'Biennial' | 'Triennial' | 'Continuous' | 'Irregular' | 'continual' | 'daily' | 'weekly' | 'fortnightly' | 'monthly' | 'quarterly' | 'biannually' | 'annually' | 'asNeeded' | 'irregular' | 'notPlanned' | 'unknown'

