/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthenticationGetJwtResponseJwts } from './authentication-get-jwt-response-jwts';

/**
 * 
 * @export
 * @interface AuthenticationGetJwtResponse
 */
export interface AuthenticationGetJwtResponse {
    /**
     * 
     * @type {AuthenticationGetJwtResponseJwts}
     * @memberof AuthenticationGetJwtResponse
     */
    'jwts'?: AuthenticationGetJwtResponseJwts;
}

