/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AuthenticationGetJwtResponseJwtsAgrimetrics
 */
export interface AuthenticationGetJwtResponseJwtsAgrimetrics {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationGetJwtResponseJwtsAgrimetrics
     */
    'token_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationGetJwtResponseJwtsAgrimetrics
     */
    'access_token'?: string;
}

