/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AuthenticationGetJwtRequest
 */
export interface AuthenticationGetJwtRequest {
    /**
     * Agrimetrics Catalog username
     * @type {string}
     * @memberof AuthenticationGetJwtRequest
     */
    'username'?: string;
    /**
     * Agrimetrics Catalog password
     * @type {string}
     * @memberof AuthenticationGetJwtRequest
     */
    'password'?: string;
}

