/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BandStats } from './band-stats';

/**
 * 
 * @export
 * @interface Band
 */
export interface Band {
    /**
     * 
     * @type {string}
     * @memberof Band
     */
    'index': string;
    /**
     * 
     * @type {BandStats}
     * @memberof Band
     */
    'stats': BandStats;
    /**
     * 
     * @type {number}
     * @memberof Band
     */
    'totalNumPixels': number;
    /**
     * This object represents the number of pixel-value occurrences in the band. For example, a pixel-value `12.0` that occurs `3` times would be represented as `\"12.0\": 3` in this object. 
     * @type {{ [key: string]: number; }}
     * @memberof Band
     */
    'pixelCounts': { [key: string]: number; };
}

