/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Entitlements } from './entitlements';
import { IdentityInput } from './identity-input';

/**
 * 
 * @export
 * @interface BatchIdentityInputEntitlementsInner
 */
export interface BatchIdentityInputEntitlementsInner {
    /**
     * 
     * @type {IdentityInput}
     * @memberof BatchIdentityInputEntitlementsInner
     */
    'identity': IdentityInput;
    /**
     * 
     * @type {Entitlements}
     * @memberof BatchIdentityInputEntitlementsInner
     */
    'entitlements': Entitlements;
}

