/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Billable
 */
export interface Billable {
    /**
     * 
     * @type {string}
     * @memberof Billable
     */
    'billingDataType': string;
    /**
     * 
     * @type {string}
     * @memberof Billable
     */
    'billingCreditType': string;
    /**
     * 
     * @type {number}
     * @memberof Billable
     */
    'billingCreditCost': number;
}

