/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BoundingBoxCoordinates
 */
export interface BoundingBoxCoordinates {
    /**
     * 
     * @type {number}
     * @memberof BoundingBoxCoordinates
     */
    'minlat': number;
    /**
     * 
     * @type {number}
     * @memberof BoundingBoxCoordinates
     */
    'minlon': number;
    /**
     * 
     * @type {number}
     * @memberof BoundingBoxCoordinates
     */
    'maxlat': number;
    /**
     * 
     * @type {number}
     * @memberof BoundingBoxCoordinates
     */
    'maxlon': number;
}

