/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BoundingBoxCoordinates } from './bounding-box-coordinates';

/**
 * 
 * @export
 * @interface BoundingBox
 */
export interface BoundingBox {
    /**
     * 
     * @type {string}
     * @memberof BoundingBox
     */
    'type': BoundingBoxTypeEnum;
    /**
     * 
     * @type {BoundingBoxCoordinates}
     * @memberof BoundingBox
     */
    'coordinates': BoundingBoxCoordinates;
}

type BoundingBoxTypeEnum = 'bounding-box'


