/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The value of the category
 * @export
 * @enum {string}
 */
export type CategoryValue = 'free' | 'standard' | 'premium' | 'on-request'

