/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Concept
 */
export interface Concept {
    /**
     * The value of the concept
     * @type {string}
     * @memberof Concept
     */
    'value': string;
    /**
     * The label of the concept
     * @type {string}
     * @memberof Concept
     */
    'label': string;
}

