/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * Organisation name for this contact
     * @type {string}
     * @memberof Contact
     */
    'organisationName': string;
    /**
     * Individual name for this contact
     * @type {string}
     * @memberof Contact
     */
    'individualName'?: string;
    /**
     * Position of this contact within their organisation
     * @type {string}
     * @memberof Contact
     */
    'positionName'?: string;
    /**
     * Email address for this contact
     * @type {string}
     * @memberof Contact
     */
    'emailAddress'?: string;
    /**
     * The role of this contact as it relates to the data set
     * @type {string}
     * @memberof Contact
     */
    'role': ContactRoleEnum;
}

type ContactRoleEnum = 'resourceProvider' | 'custodian' | 'owner' | 'user' | 'distributor' | 'originator' | 'pointOfContact' | 'principalInvestigator' | 'processor' | 'publisher' | 'author'


