/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Exchange } from './exchange';

/**
 * 
 * @export
 * @interface CreateFromTemplatePayload
 */
export interface CreateFromTemplatePayload {
    /**
     * Title for the data set.
     * @type {string}
     * @memberof CreateFromTemplatePayload
     */
    'title'?: string;
    /**
     * Description of the data set.
     * @type {string}
     * @memberof CreateFromTemplatePayload
     */
    'description'?: string;
    /**
     * The ID of a template in the catalog
     * @type {string}
     * @memberof CreateFromTemplatePayload
     */
    'templateId': string;
    /**
     * 
     * @type {Exchange}
     * @memberof CreateFromTemplatePayload
     */
    'exchange'?: Exchange;
}

