/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Creator
 */
export interface Creator {
    /**
     * The value of the creator
     * @type {string}
     * @memberof Creator
     */
    'value'?: string;
    /**
     * The label of the creator
     * @type {string}
     * @memberof Creator
     */
    'label'?: string;
}

