/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BatchIdentityInputEntitlementsInner } from './batch-identity-input-entitlements-inner';
import { DataSetPatch } from './data-set-patch';
import { DataSetTemplateEntityAllOf } from './data-set-template-entity-all-of';
import { DataSetTemplateMetadata } from './data-set-template-metadata';
import { Entitlements } from './entitlements';
import { Exchange } from './exchange';

/**
 * @type DataSetTemplateEntity
 * Returned from API responses, includes id and other required properties
 * @export
 */
export type DataSetTemplateEntity = DataSetTemplateEntityAllOf & DataSetTemplateMetadata;


