/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DataSetListAllDataSetsPublishedStatusParameterInnerOneOf } from './data-set-list-all-data-sets-published-status-parameter-inner-one-of';
import { PublishedStatus } from './published-status';

/**
 * @type DataSetListAllDataSetsPublishedStatusParameterInner
 * @export
 */
export type DataSetListAllDataSetsPublishedStatusParameterInner = DataSetListAllDataSetsPublishedStatusParameterInnerOneOf | PublishedStatus;


