/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BatchIdentityInputEntitlementsInner } from './batch-identity-input-entitlements-inner';
import { DataSetPatch } from './data-set-patch';
import { Entitlements } from './entitlements';

/**
 * Used as params for PATCH requests
 * @export
 * @interface DataSetTemplatePatchMetadata
 */
export interface DataSetTemplatePatchMetadata {
    /**
     * 
     * @type {string}
     * @memberof DataSetTemplatePatchMetadata
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof DataSetTemplatePatchMetadata
     */
    'name'?: string;
    /**
     * 
     * @type {DataSetPatch}
     * @memberof DataSetTemplatePatchMetadata
     */
    'dataSet'?: DataSetPatch;
    /**
     * 
     * @type {Array<BatchIdentityInputEntitlementsInner>}
     * @memberof DataSetTemplatePatchMetadata
     */
    'entitlements'?: Array<BatchIdentityInputEntitlementsInner>;
    /**
     * 
     * @type {Entitlements}
     * @memberof DataSetTemplatePatchMetadata
     */
    'creatorEntitlements'?: Entitlements;
}

