/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Licensing information and access constraint
 * @export
 * @interface DataSetPatchLicence
 */
export interface DataSetPatchLicence {
    /**
     * the name or contents of the licence
     * @type {string}
     * @memberof DataSetPatchLicence
     */
    'text': string;
    /**
     * link to the contents of the licence
     * @type {string}
     * @memberof DataSetPatchLicence
     */
    'url'?: string;
    /**
     * INSPIRE Limitations On Public Access, see: https://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess
     * @type {string}
     * @memberof DataSetPatchLicence
     */
    'useLimitationStatement'?: string;
    /**
     * copyright statement
     * @type {string}
     * @memberof DataSetPatchLicence
     */
    'attributionStatement'?: string;
    /**
     * INSPIRE Conditions Applying To Access and Use, see: https://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse
     * @type {string}
     * @memberof DataSetPatchLicence
     */
    'useConstraints'?: string;
}

