/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DataSetPatchTemporalExtent
 */
export interface DataSetPatchTemporalExtent {
    /**
     * The beginning of the period of time covered by the data set.
     * @type {string}
     * @memberof DataSetPatchTemporalExtent
     */
    'begin': string;
    /**
     * The end of the period of time covered by the data set. If empty, the collection of data is ongoing.
     * @type {string}
     * @memberof DataSetPatchTemporalExtent
     */
    'end'?: string;
}

