/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccrualPeriodicity } from './accrual-periodicity';
import { BasicDataSetInfo } from './basic-data-set-info';
import { CategoryValue } from './category-value';
import { Contact } from './contact';
import { DataFormat } from './data-format';
import { DataSetDataSet } from './data-set-data-set';
import { DataSetDerivedFromInner } from './data-set-derived-from-inner';
import { DataSetDistributionsInner } from './data-set-distributions-inner';
import { DataSetSampleData } from './data-set-sample-data';
import { DataSetServicesInner } from './data-set-services-inner';
import { DraftStatus } from './draft-status';
import { Entitlement } from './entitlement';
import { EntryType } from './entry-type';
import { Exchange } from './exchange';
import { GeospatialExtent } from './geospatial-extent';
import { ImageRepresentation } from './image-representation';
import { Licence } from './licence';
import { PublicContact } from './public-contact';
import { PublishedStatus } from './published-status';
import { Resource } from './resource';
import { SpatialCoverage } from './spatial-coverage';
import { TaxonomyKeywords } from './taxonomy-keywords';
import { Topic } from './topic';
import { WorkflowKeywords } from './workflow-keywords';

/**
 * 
 * @export
 * @interface DataSet
 */
export interface DataSet {
    /**
     * List of tags on this data set.
     * @type {Array<string>}
     * @memberof DataSet
     */
    'tags'?: Array<string>;
    /**
     * Summary of the data set.
     * @type {string}
     * @memberof DataSet
     */
    'summary'?: string;
    /**
     * Title for the data set.
     * @type {string}
     * @memberof DataSet
     */
    'title': string;
    /**
     * Description of the data set.
     * @type {string}
     * @memberof DataSet
     */
    'description': string;
    /**
     * The ID of a dataset in the catalog
     * @type {string}
     * @memberof DataSet
     */
    'id'?: string;
    /**
     * The type of the entry, data set or model
     * @type {EntryType}
     * @memberof DataSet
     */
    'entryType': EntryType;
    /**
     * 
     * @type {Exchange}
     * @memberof DataSet
     */
    'exchange'?: Exchange;
    /**
     * 
     * @type {Array<string>}
     * @memberof DataSet
     */
    'alternativeTitles'?: Array<string>;
    /**
     * Scoring URI of the model.
     * @type {string}
     * @memberof DataSet
     */
    'scoringURI'?: string;
    /**
     * Endpoint key for the model.
     * @type {string}
     * @memberof DataSet
     */
    'endpointKey'?: string;
    /**
     * Whether the current user is the owner of this data set.
     * @type {boolean}
     * @memberof DataSet
     */
    'isOwner'?: boolean;
    /**
     * The ID of the publisher.
     * @type {string}
     * @memberof DataSet
     */
    'publisher'?: string;
    /**
     * Data set creation timestamp.
     * @type {number}
     * @memberof DataSet
     */
    'createdAt'?: number;
    /**
     * Data set publication timestamp.
     * @type {number}
     * @memberof DataSet
     */
    'published'?: number;
    /**
     * Metadata last-modification timestmap.
     * @type {number}
     * @memberof DataSet
     */
    'metadataModified'?: number;
    /**
     * Other data sets using this data set.
     * @type {Array<BasicDataSetInfo>}
     * @memberof DataSet
     */
    'usedBy'?: Array<BasicDataSetInfo>;
    /**
     * Data sets used to generate this data set. When updating a data set, use an array of IDs. When GETting the data set, the return type will be `BasicDataSetInfo`. 
     * @type {Array<DataSetDerivedFromInner>}
     * @memberof DataSet
     */
    'derivedFrom'?: Array<DataSetDerivedFromInner>;
    /**
     * Entitlements for the current user.
     * @type {Array<Entitlement>}
     * @memberof DataSet
     */
    'entitlements'?: Array<Entitlement>;
    /**
     * Array of entitlements by user identity.
     * @type {{ [key: string]: Array<Entitlement>; }}
     * @memberof DataSet
     */
    'entitlementsByIdentity'?: { [key: string]: Array<Entitlement>; };
    /**
     * Creator of the data set.
     * @type {string}
     * @memberof DataSet
     */
    'creator'?: string;
    /**
     * Free text description about the reliability of this dataset.
     * @type {string}
     * @memberof DataSet
     */
    'dataReliability'?: string;
    /**
     * License of the data set.
     * @type {string}
     * @memberof DataSet
     * @deprecated
     */
    'license'?: string;
    /**
     * 
     * @type {Licence}
     * @memberof DataSet
     */
    'licence'?: Licence;
    /**
     * DEPRECATED. This has been replaced with the resources attribute. Reference URI of the data set.
     * @type {string}
     * @memberof DataSet
     * @deprecated
     */
    'landingPage'?: string;
    /**
     * Links containing more information on the data set
     * @type {Array<Resource>}
     * @memberof DataSet
     */
    'resources'?: Array<Resource>;
    /**
     * Format of the data set
     * @type {Array<DataFormat>}
     * @memberof DataSet
     */
    'dataFormats'?: Array<DataFormat>;
    /**
     * Pricing description of the data set.
     * @type {string}
     * @memberof DataSet
     */
    'pricingDescription'?: string;
    /**
     * The geo spatial coverage of the data set.
     * @type {SpatialCoverage}
     * @memberof DataSet
     */
    'spatialCoverage'?: SpatialCoverage;
    /**
     * The resolution of data set in meters.
     * @type {number}
     * @memberof DataSet
     */
    'spatialResolution'?: number;
    /**
     * 
     * @type {GeospatialExtent}
     * @memberof DataSet
     */
    'geospatialExtent'?: GeospatialExtent;
    /**
     * The time frame this data set covers.
     * @type {string}
     * @memberof DataSet
     */
    'temporalCoverage'?: string;
    /**
     * The sampling time period of the data set.
     * @type {string}
     * @memberof DataSet
     */
    'temporalResolution'?: DataSetTemporalResolutionEnum;
    /**
     * Accrual periodicity options
     * @type {AccrualPeriodicity}
     * @memberof DataSet
     */
    'accrualPeriodicity'?: AccrualPeriodicity;
    /**
     * 
     * @type {Array<DataSetDistributionsInner>}
     * @memberof DataSet
     */
    'distributions'?: Array<DataSetDistributionsInner>;
    /**
     * The date when the data set was issued.
     * @type {string}
     * @memberof DataSet
     */
    'issued'?: string;
    /**
     * An timestamp of when the data in this dataset was last updated
     * @type {number}
     * @memberof DataSet
     */
    'modified'?: number;
    /**
     * List of keywords on this data set. keywords is deprecated - use tags instead
     * @type {Array<string>}
     * @memberof DataSet
     * @deprecated
     */
    'keywords'?: Array<string>;
    /**
     * List of topics on this data set
     * @type {Array<Topic>}
     * @memberof DataSet
     */
    'topics'?: Array<Topic>;
    /**
     * List of workflow keywords on this data set
     * @type {Array<WorkflowKeywords>}
     * @memberof DataSet
     */
    'workflowKeywords'?: Array<WorkflowKeywords>;
    /**
     * List of keywords based on specific taxonomies
     * @type {Array<TaxonomyKeywords>}
     * @memberof DataSet
     */
    'taxonomyKeywords'?: Array<TaxonomyKeywords>;
    /**
     * The value of the category
     * @type {CategoryValue}
     * @memberof DataSet
     */
    'category'?: CategoryValue;
    /**
     * Whether or not this data set should be displayed in the index.
     * @type {string}
     * @memberof DataSet
     */
    'visibility'?: DataSetVisibilityEnum;
    /**
     * List of concepts on this data set. Check the concepts endpoint to see valid values.
     * @type {Array<string>}
     * @memberof DataSet
     */
    'concepts'?: Array<string>;
    /**
     * 
     * @type {DataSetDataSet}
     * @memberof DataSet
     */
    'dataSet'?: DataSetDataSet;
    /**
     * List of services available on the data set
     * @type {Array<DataSetServicesInner>}
     * @memberof DataSet
     */
    'services'?: Array<DataSetServicesInner>;
    /**
     * 
     * @type {DataSetSampleData}
     * @memberof DataSet
     */
    'sampleData'?: DataSetSampleData;
    /**
     * 
     * @type {ImageRepresentation}
     * @memberof DataSet
     */
    'image'?: ImageRepresentation;
    /**
     * URL to the specification of the coordinate system used in the data
     * @type {string}
     * @memberof DataSet
     */
    'coordinateReferenceSystemId'?: string;
    /**
     * Type of the geospatial data
     * @type {string}
     * @memberof DataSet
     */
    'spatialRepresentationType'?: string;
    /**
     * Information about the creation and quality assurance process of the dataset
     * @type {string}
     * @memberof DataSet
     */
    'lineage'?: string;
    /**
     * Information about which template was used to create the dataset record
     * @type {string}
     * @memberof DataSet
     */
    'fromTemplate'?: string;
    /**
     * List of contacts for this data set
     * @type {Array<Contact>}
     * @memberof DataSet
     */
    'contacts'?: Array<Contact>;
    /**
     * 
     * @type {Contact}
     * @memberof DataSet
     */
    'metadataContact'?: Contact;
    /**
     * 
     * @type {PublicContact}
     * @memberof DataSet
     */
    'publicContact'?: PublicContact;
    /**
     * Approval for access status number
     * @type {number}
     * @memberof DataSet
     */
    'approvalForAccessNumber'?: number;
    /**
     * Approval for access status value
     * @type {string}
     * @memberof DataSet
     */
    'approvalForAccessStatus'?: DataSetApprovalForAccessStatusEnum;
    /**
     * Language used on the data set
     * @type {string}
     * @memberof DataSet
     */
    'language'?: string;
    /**
     * Character set used on the data set
     * @type {string}
     * @memberof DataSet
     */
    'characterSet'?: string;
    /**
     * Hierarchy level of the data set
     * @type {string}
     * @memberof DataSet
     */
    'hierarchyLevel'?: string;
    /**
     * Language used on the metadata
     * @type {string}
     * @memberof DataSet
     */
    'metadataLanguage'?: string;
    /**
     * Character set used on the metadata
     * @type {string}
     * @memberof DataSet
     */
    'metadataCharacterSet'?: string;
    /**
     * 
     * @type {string}
     * @memberof DataSet
     */
    'metadataStandardName'?: string;
    /**
     * 
     * @type {string}
     * @memberof DataSet
     */
    'metadataStandardVersion'?: string;
    /**
     * The workflow status of this data set\'s draft
     * @type {DraftStatus}
     * @memberof DataSet
     */
    'draftStatus'?: DraftStatus;
    /**
     * Any notes added during review of the data set
     * @type {string}
     * @memberof DataSet
     */
    'draftNotes'?: string;
    /**
     * The publication status of this data set. Published data-sets have been approved by an admin
     * @type {PublishedStatus}
     * @memberof DataSet
     */
    'publishedStatus'?: PublishedStatus;
}

type DataSetTemporalResolutionEnum = 'P1Y' | 'P1M' | 'P1D' | 'PT1H' | 'PT1M' | 'PT1S'
type DataSetVisibilityEnum = 'visible' | 'hidden'
type DataSetApprovalForAccessStatusEnum = 'AfA (Information Requests only)' | 'AfA (Public Register)' | 'AfA (Publication Scheme and Information for Re-Use Register)' | 'AfA (Publication Scheme)' | 'Not AfA (To be Assessessed with Guidance)' | 'Not AfA (To be Assessed)' | 'Not Applicable - Third Party Dataset' | 'Open Data Risk Assessment'


