/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The geospatial extent of the data on the data set
 * @export
 * @interface DataSetPatchGeospatialExtent
 */
export interface DataSetPatchGeospatialExtent {
    /**
     * 
     * @type {number}
     * @memberof DataSetPatchGeospatialExtent
     */
    'northBoundLatitude': number;
    /**
     * 
     * @type {number}
     * @memberof DataSetPatchGeospatialExtent
     */
    'eastBoundLongitude': number;
    /**
     * 
     * @type {number}
     * @memberof DataSetPatchGeospatialExtent
     */
    'southBoundLatitude': number;
    /**
     * 
     * @type {number}
     * @memberof DataSetPatchGeospatialExtent
     */
    'westBoundLongitude': number;
}

