/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Service URI and Label
 * @export
 * @interface DataSetServicesInner
 */
export interface DataSetServicesInner {
    /**
     * 
     * @type {string}
     * @memberof DataSetServicesInner
     */
    'uri'?: string;
    /**
     * 
     * @type {string}
     * @memberof DataSetServicesInner
     */
    'label'?: string;
}

