/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DataRequestResponseInner
 */
export interface DataRequestResponseInner {
    /**
     * The ID of the data request
     * @type {string}
     * @memberof DataRequestResponseInner
     */
    'requestId': string;
    /**
     * The ID of the dataset that the data request relates to
     * @type {string}
     * @memberof DataRequestResponseInner
     */
    'datasetId': string;
    /**
     * The name of the dataset that the data request relates to
     * @type {string}
     * @memberof DataRequestResponseInner
     */
    'datasetName': string;
    /**
     * The status of the data request
     * @type {string}
     * @memberof DataRequestResponseInner
     */
    'status': DataRequestResponseInnerStatusEnum;
    /**
     * The date the data request was made
     * @type {string}
     * @memberof DataRequestResponseInner
     */
    'requestedDate': string;
    /**
     * The requesters email address
     * @type {any}
     * @memberof DataRequestResponseInner
     */
    'requesterEmail': any;
}

type DataRequestResponseInnerStatusEnum = 'pending' | 'approved' | 'denied' | 'cancelled'


