/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BatchIdentityInputEntitlementsInner } from './batch-identity-input-entitlements-inner';
import { DataSetPatch } from './data-set-patch';
import { Entitlements } from './entitlements';
import { Exchange } from './exchange';

/**
 * Used as params for POST/PUT requests
 * @export
 * @interface DataSetTemplateMetadata
 */
export interface DataSetTemplateMetadata {
    /**
     * 
     * @type {string}
     * @memberof DataSetTemplateMetadata
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof DataSetTemplateMetadata
     */
    'name': string;
    /**
     * 
     * @type {DataSetPatch}
     * @memberof DataSetTemplateMetadata
     */
    'dataSet'?: DataSetPatch;
    /**
     * 
     * @type {Array<BatchIdentityInputEntitlementsInner>}
     * @memberof DataSetTemplateMetadata
     */
    'entitlements'?: Array<BatchIdentityInputEntitlementsInner>;
    /**
     * 
     * @type {Entitlements}
     * @memberof DataSetTemplateMetadata
     */
    'creatorEntitlements'?: Entitlements;
    /**
     * 
     * @type {Exchange}
     * @memberof DataSetTemplateMetadata
     */
    'exchange'?: Exchange;
}

