/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DataRequest
 */
export interface DataRequest {
    /**
     * The name of the project the data is for
     * @type {string}
     * @memberof DataRequest
     */
    'projectName': string;
    /**
     * The name of the project manager who can approve the request
     * @type {string}
     * @memberof DataRequest
     */
    'projectManagerName': string;
    /**
     * The email address of the project manager who can approve the request
     * @type {string}
     * @memberof DataRequest
     */
    'projectManagerEmail': string;
    /**
     * The ID of the dataset that the data request relates to
     * @type {string}
     * @memberof DataRequest
     */
    'datasetId': string;
    /**
     * The name of the dataset that the data request relates to
     * @type {string}
     * @memberof DataRequest
     */
    'datasetName': string;
    /**
     * The area of interest that the user is requesting access to as a stringified GeoJSON
     * @type {string}
     * @memberof DataRequest
     */
    'geoJsonAOI'?: string;
    /**
     * The area of interest that the user is requesting access to as a zipped shapefile
     * @type {Uint8Array | File | buffer.File}
     * @memberof DataRequest
     */
    'shapefileAOI'?: Uint8Array | File | buffer.File;
    /**
     * The format the user would like the data to be provided in
     * @type {string}
     * @memberof DataRequest
     */
    'requestedFormat': DataRequestRequestedFormatEnum;
}

type DataRequestRequestedFormatEnum = 'application/geo+json' | 'application/gml+xml; version=3.2' | 'application/vnd.google-earth.kml+xml' | 'application/zipped-shapefile' | 'application/x.gdb+zip' | 'application/x.mid-mif+zip' | 'application/x.tab+zip' | 'application/dxf' | 'image/tiff'


