/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Contact for the metadata on this data set
 * @export
 * @interface DataSetPatchMetadataContact
 */
export interface DataSetPatchMetadataContact {
    /**
     * Organisation name for this contact
     * @type {string}
     * @memberof DataSetPatchMetadataContact
     */
    'organisationName': string;
    /**
     * Individual name for this contact
     * @type {string}
     * @memberof DataSetPatchMetadataContact
     */
    'individualName'?: string;
    /**
     * Email address for this contact
     * @type {string}
     * @memberof DataSetPatchMetadataContact
     */
    'emailAddress'?: string;
    /**
     * The role of this contact as it relates to the data set
     * @type {string}
     * @memberof DataSetPatchMetadataContact
     */
    'role': DataSetPatchMetadataContactRoleEnum;
}

type DataSetPatchMetadataContactRoleEnum = 'resourceProvider' | 'custodian' | 'owner' | 'user' | 'distributor' | 'originator' | 'pointOfContact' | 'principalInvestigator' | 'processor' | 'publisher' | 'author'


