/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The workflow status of this data set\'s draft
 * @export
 * @enum {string}
 */
export type DraftStatus = 'submitted' | 'approved' | 'rejected'

