/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EntitlementsCatalog
 */
export interface EntitlementsCatalog {
    /**
     * 
     * @type {boolean}
     * @memberof EntitlementsCatalog
     */
    'read'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntitlementsCatalog
     */
    'readSensitive'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntitlementsCatalog
     */
    'write'?: boolean;
}

