/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EntryUpdateResponse
 */
export interface EntryUpdateResponse {
    /**
     * A message describing the result of the operation
     * @type {string}
     * @memberof EntryUpdateResponse
     */
    'status'?: string;
    /**
     * The ID for the new catalog entry.
     * @type {string}
     * @memberof EntryUpdateResponse
     */
    'id'?: string;
}

