/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GeoJSONPolygonCoordinatesInnerInnerInner } from './geo-jsonpolygon-coordinates-inner-inner-inner';

/**
 * 
 * @export
 * @interface GeoJSONMultiPolygon
 */
export interface GeoJSONMultiPolygon {
    /**
     * 
     * @type {string}
     * @memberof GeoJSONMultiPolygon
     */
    'type': GeoJSONMultiPolygonTypeEnum;
    /**
     * 
     * @type {Array<Array<Array<Array<GeoJSONPolygonCoordinatesInnerInnerInner>>>>}
     * @memberof GeoJSONMultiPolygon
     */
    'coordinates': Array<Array<Array<Array<GeoJSONPolygonCoordinatesInnerInnerInner>>>>;
}

type GeoJSONMultiPolygonTypeEnum = 'MultiPolygon'


