/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GeoJSONPolygonCoordinatesInnerInnerInner } from './geo-jsonpolygon-coordinates-inner-inner-inner';

/**
 * 
 * @export
 * @interface GeoJSONPolygon
 */
export interface GeoJSONPolygon {
    /**
     * 
     * @type {string}
     * @memberof GeoJSONPolygon
     */
    'type': GeoJSONPolygonTypeEnum;
    /**
     * 
     * @type {Array<Array<Array<GeoJSONPolygonCoordinatesInnerInnerInner>>>}
     * @memberof GeoJSONPolygon
     */
    'coordinates': Array<Array<Array<GeoJSONPolygonCoordinatesInnerInnerInner>>>;
}

type GeoJSONPolygonTypeEnum = 'Polygon'


