/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GeoJSONPolygonCoordinatesInnerInnerInner } from './geo-jsonpolygon-coordinates-inner-inner-inner';

/**
 * This is a GeoJSON Point. The coordinates array must be EPSG:4326 with [longitude,latitude] order.
 * @export
 * @interface GeoJSONPoint
 */
export interface GeoJSONPoint {
    /**
     * 
     * @type {string}
     * @memberof GeoJSONPoint
     */
    'type': GeoJSONPointTypeEnum;
    /**
     * 
     * @type {Array<GeoJSONPolygonCoordinatesInnerInnerInner>}
     * @memberof GeoJSONPoint
     */
    'coordinates': Array<GeoJSONPolygonCoordinatesInnerInnerInner>;
}

type GeoJSONPointTypeEnum = 'Point'


