/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GeospatialExtent
 */
export interface GeospatialExtent {
    /**
     * 
     * @type {number}
     * @memberof GeospatialExtent
     */
    'northBoundLatitude': number;
    /**
     * 
     * @type {number}
     * @memberof GeospatialExtent
     */
    'eastBoundLongitude': number;
    /**
     * 
     * @type {number}
     * @memberof GeospatialExtent
     */
    'southBoundLatitude': number;
    /**
     * 
     * @type {number}
     * @memberof GeospatialExtent
     */
    'westBoundLongitude': number;
}

