/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Name of group being harvested
 * @export
 * @enum {string}
 */
export type GroupCode = 'apha' | 'defra' | 'ea' | 'ne' | 'rpa'

