/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An entity, such as a user or organisation.
 * @export
 * @interface IdentityInput
 */
export interface IdentityInput {
    /**
     * The Auth0 id of a user, or uuid of another identity
     * @type {string}
     * @memberof IdentityInput
     */
    'id'?: string;
    /**
     * The email address of a user
     * @type {string}
     * @memberof IdentityInput
     */
    'email'?: string;
    /**
     * The name of the user. Will be ignored, but allowed so GET data can be round-tripped.
     * @type {string}
     * @memberof IdentityInput
     */
    'name'?: string;
    /**
     * The type of the identity
     * @type {string}
     * @memberof IdentityInput
     */
    'type': IdentityInputTypeEnum;
}

type IdentityInputTypeEnum = 'user' | 'organisation' | 'public'


