/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Entitlements } from './entitlements';
import { IdentityEntitlementsIdentity } from './identity-entitlements-identity';

/**
 * Entitlements for an identity on a resource, and details of the identity
 * @export
 * @interface IdentityEntitlements
 */
export interface IdentityEntitlements {
    /**
     * 
     * @type {IdentityEntitlementsIdentity}
     * @memberof IdentityEntitlements
     */
    'identity'?: IdentityEntitlementsIdentity;
    /**
     * 
     * @type {Entitlements}
     * @memberof IdentityEntitlements
     */
    'entitlements'?: Entitlements;
}

