/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The entity with the entitlements on this resource
 * @export
 * @interface IdentityEntitlementsIdentity
 */
export interface IdentityEntitlementsIdentity {
    /**
     * 
     * @type {string}
     * @memberof IdentityEntitlementsIdentity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityEntitlementsIdentity
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityEntitlementsIdentity
     */
    'name'?: string;
}

