/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The author of the image and a link to their website.
 * @export
 * @interface ImageRepresentationAuthor
 */
export interface ImageRepresentationAuthor {
    /**
     * 
     * @type {string}
     * @memberof ImageRepresentationAuthor
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageRepresentationAuthor
     */
    'url'?: string;
}

