/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LayerLinks } from './layer-links';

/**
 * 
 * @export
 * @interface Layer
 */
export interface Layer {
    /**
     * 
     * @type {string}
     * @memberof Layer
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof Layer
     */
    'layerId': string;
    /**
     * 
     * @type {LayerLinks}
     * @memberof Layer
     */
    'links': LayerLinks;
}

