/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ManageLayerSetStyleRequest
 */
export interface ManageLayerSetStyleRequest {
    /**
     * 
     * @type {Uint8Array | File | buffer.File}
     * @memberof ManageLayerSetStyleRequest
     */
    'file'?: Uint8Array | File | buffer.File;
}

