/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ManageLayerAddGeoTiffRequest
 */
export interface ManageLayerAddGeoTiffRequest {
    /**
     * 
     * @type {string}
     * @memberof ManageLayerAddGeoTiffRequest
     */
    'datetime'?: string;
    /**
     * The file to upload.
     * @type {Uint8Array | File | buffer.File}
     * @memberof ManageLayerAddGeoTiffRequest
     */
    'file'?: Uint8Array | File | buffer.File;
}

