/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ManageLayerIngestFileRequest
 */
export interface ManageLayerIngestFileRequest {
    /**
     * 
     * @type {string}
     * @memberof ManageLayerIngestFileRequest
     */
    'fileId': string;
    /**
     * 
     * @type {string}
     * @memberof ManageLayerIngestFileRequest
     */
    'fileName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ManageLayerIngestFileRequest
     */
    'datetime'?: string;
}

