/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type OutputFormats = 'shape-zip' | 'application/json' | 'csv' | 'GML3' | 'image/tiff' | 'KML' | 'OGR-GDB' | 'OGR-MIF' | 'OGR-TAB' | 'DXF'

