/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GeoJSONPoint } from './geo-jsonpoint';

/**
 * 
 * @export
 * @interface PointSearchBase
 */
export interface PointSearchBase {
    /**
     * 
     * @type {GeoJSONPoint}
     * @memberof PointSearchBase
     */
    'geometry': GeoJSONPoint;
    /**
     * 
     * @type {number}
     * @memberof PointSearchBase
     */
    'distance': number;
    /**
     * 
     * @type {string}
     * @memberof PointSearchBase
     */
    'time'?: string;
}

