/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GeneralGeometry } from './general-geometry';
import { OutputFormats } from './output-formats';
import { PolygonOrBBoxSearchAllOf } from './polygon-or-bbox-search-all-of';
import { PolygonOrBBoxSearchBase } from './polygon-or-bbox-search-base';

/**
 * @type PolygonOrBBoxSearch
 * @export
 */
export type PolygonOrBBoxSearch = PolygonOrBBoxSearchAllOf & PolygonOrBBoxSearchBase;


