/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The publication status of this data set. Published data-sets have been approved by an admin
 * @export
 * @enum {string}
 */
export type PublishedStatus = 'published' | 'retired'

