/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface QueryLayerCutShapeBoundaryAndRetrieve406Response
 */
export interface QueryLayerCutShapeBoundaryAndRetrieve406Response {
    /**
     * 
     * @type {string}
     * @memberof QueryLayerCutShapeBoundaryAndRetrieve406Response
     */
    'message': string;
}

