/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GeoJSONPoint } from './geo-jsonpoint';
import { PointSearchBase } from './point-search-base';
import { PolygonOrBBoxSearchBase } from './polygon-or-bbox-search-base';

/**
 * @type QueryLayerCalculateCostRequest
 * @export
 */
export type QueryLayerCalculateCostRequest = PointSearchBase | PolygonOrBBoxSearchBase;


