/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Billable } from './billable';

/**
 * 
 * @export
 * @interface ServiceDefinitionResponse
 */
export interface ServiceDefinitionResponse {
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'layerId': string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'datasetId': string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'layerName': string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'service': ServiceDefinitionResponseServiceEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceDefinitionResponse
     */
    'temporal'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'datastore'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'geoserverHostName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'geometryField'?: string;
    /**
     * 
     * @type {Billable}
     * @memberof ServiceDefinitionResponse
     */
    'billable'?: Billable;
    /**
     * 
     * @type {number}
     * @memberof ServiceDefinitionResponse
     */
    'defaultEPSGCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'WMS': ServiceDefinitionResponseWMSEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'WMTS': ServiceDefinitionResponseWMTSEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'WFS': ServiceDefinitionResponseWFSEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'WCS': ServiceDefinitionResponseWCSEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'OGCApiFeatures': ServiceDefinitionResponseOgCApiFeaturesEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionResponse
     */
    'OGCApiTiles': ServiceDefinitionResponseOgCApiTilesEnum;
}

type ServiceDefinitionResponseServiceEnum = 'WCS' | 'WFS'
type ServiceDefinitionResponseWMSEnum = 'Y' | 'N'
type ServiceDefinitionResponseWMTSEnum = 'Y' | 'N'
type ServiceDefinitionResponseWFSEnum = 'Y' | 'N'
type ServiceDefinitionResponseWCSEnum = 'Y' | 'N'
type ServiceDefinitionResponseOgCApiFeaturesEnum = 'Y' | 'N'
type ServiceDefinitionResponseOgCApiTilesEnum = 'Y' | 'N'


