/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Billable } from './billable';

/**
 * 
 * @export
 * @interface ServiceDefinitionUpdateExistingDefinitionRequest
 */
export interface ServiceDefinitionUpdateExistingDefinitionRequest {
    /**
     * 
     * @type {Billable}
     * @memberof ServiceDefinitionUpdateExistingDefinitionRequest
     */
    'billable'?: Billable;
    /**
     * 
     * @type {number}
     * @memberof ServiceDefinitionUpdateExistingDefinitionRequest
     */
    'defaultEPSGCode'?: number;
}

