/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Billable } from './billable';

/**
 * 
 * @export
 * @interface ServiceDefinition
 */
export interface ServiceDefinition {
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'datasetId': string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'layerName': string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'service': ServiceDefinitionServiceEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'WFS': ServiceDefinitionWFSEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'WCS': ServiceDefinitionWCSEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'WMS': ServiceDefinitionWMSEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'WMTS': ServiceDefinitionWMTSEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'OGCApiFeatures': ServiceDefinitionOgCApiFeaturesEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'OGCApiTiles': ServiceDefinitionOgCApiTilesEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceDefinition
     */
    'temporal'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'datastore'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'geoserverHostName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinition
     */
    'geometryField'?: string;
    /**
     * 
     * @type {Billable}
     * @memberof ServiceDefinition
     */
    'billable'?: Billable;
    /**
     * 
     * @type {number}
     * @memberof ServiceDefinition
     */
    'defaultEPSGCode'?: number;
}

type ServiceDefinitionServiceEnum = 'WCS' | 'WFS'
type ServiceDefinitionWFSEnum = 'Y' | 'N'
type ServiceDefinitionWCSEnum = 'Y' | 'N'
type ServiceDefinitionWMSEnum = 'Y' | 'N'
type ServiceDefinitionWMTSEnum = 'Y' | 'N'
type ServiceDefinitionOgCApiFeaturesEnum = 'Y' | 'N'
type ServiceDefinitionOgCApiTilesEnum = 'Y' | 'N'


