/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The geo spatial coverage of the data set.
 * @export
 * @enum {string}
 */
export type SpatialCoverage = 'United Kingdom' | 'England' | 'Northern Ireland' | 'Scotland' | 'Wales' | 'Canada' | 'Ethiopia' | 'France' | 'India' | 'Kenya' | 'Mexico' | 'Netherlands' | 'Spain' | 'Tanzania' | 'Uganda' | 'United States' | 'Global only'

