/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { StatusSetDraftStatusRequestStatus } from './status-set-draft-status-request-status';

/**
 * 
 * @export
 * @interface StatusSetDraftStatusRequest
 */
export interface StatusSetDraftStatusRequest {
    /**
     * 
     * @type {StatusSetDraftStatusRequestStatus}
     * @memberof StatusSetDraftStatusRequest
     */
    'status': StatusSetDraftStatusRequestStatus;
    /**
     * Any notes added during review of the data set
     * @type {string}
     * @memberof StatusSetDraftStatusRequest
     */
    'notes'?: string;
}

