/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { StatusGetCatalogApiStatusResponseLinksSelf } from './status-get-catalog-api-status-response-links-self';

/**
 * 
 * @export
 * @interface StatusGetCatalogApiStatusResponseLinks
 */
export interface StatusGetCatalogApiStatusResponseLinks {
    /**
     * 
     * @type {StatusGetCatalogApiStatusResponseLinksSelf}
     * @memberof StatusGetCatalogApiStatusResponseLinks
     */
    'self': StatusGetCatalogApiStatusResponseLinksSelf;
}

