/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Taxonomy keyword values
 * @export
 * @interface TaxonomyKeywords
 */
export interface TaxonomyKeywords {
    /**
     * 
     * @type {string}
     * @memberof TaxonomyKeywords
     */
    'valueUri': string;
    /**
     * 
     * @type {string}
     * @memberof TaxonomyKeywords
     */
    'valueLabel': string;
    /**
     * 
     * @type {string}
     * @memberof TaxonomyKeywords
     */
    'sourceUri': string;
    /**
     * 
     * @type {string}
     * @memberof TaxonomyKeywords
     */
    'sourceLabel': string;
}

