/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * topic value
 * @export
 * @enum {string}
 */
export type Topic = 'farming' | 'biota' | 'boundaries' | 'climatologyMeteorologyAtmosphere' | 'economy' | 'elevation' | 'environment' | 'geoscientificInformation' | 'health' | 'imageryBaseMapsEarthCover' | 'intelligenceMilitary' | 'inlandWaters' | 'location' | 'oceans' | 'planningCadastre' | 'society' | 'structure' | 'transportation' | 'utilitiesCommunication'

