/*
Catalog API

This API lists data sets available on Agrimetrics platform.

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Workflow keyword value
 * @export
 * @enum {string}
 */
export type WorkflowKeywords = 'OpenData' | 'NonSpatial' | 'NotOpen' | 'ConditionalData' | 'PartnerDataset' | 'InternalOnly' | 'ThirdParty' | 'DatasetBundle' | 'RetiredOpenData' | 'RetiredNotOpen' | 'RetiredConditionalData' | 'RetiredPartnerDataset' | 'RetiredInternalOnly' | 'RetiredThirdParty' | 'RetiredDatasetBundle' | 'RetiredNonSpatial'

